memory_limit=512M
upload_max_filesize=2M
post_max_size=2M
max_execution_time=300
expose_php=Off
pgsql.allow_persistent=On
pgsql.max_persistent=-1
pgsql.max_links=-1

; OPCACHE
opcache.enable=1
opcache.enable_cli=1
opcache.validate_timestamps=0
opcache.max_accelerated_files=9216
opcache.memory_consumption=256
opcache.interned_strings_buffer=12
opcache.fast_shutdown=1
opcache.enable_file_override=1
opcache.save_comments=1
